### ISSUE TITLE
Self is not defined

### ISSUE THREAD

**Issue by lukicupak** [lukevella/react-activity#17]
Hi, there is an issue with 'self' in next.js environment (during server side rendering), 
![Screenshot 2021-07-07 at 11 28 00](https://user-images.githubusercontent.com/7071926/124735549-6d3e3500-df16-11eb-904d-5d09978e497f.png)
@lukevella Could you consider updating code according to this topic https://stackoverflow.com/questions/64639839/typescript-webpack-library-generates-referenceerror-self-is-not-defined ?

**Comment by oberruti** [comment]
Hi! I have the same issue @lukevella

**Comment by lukevella** [comment]
I just published a new version. Could you let me know if this works for you?

**Comment by lukevella** [comment]
I've had a deeper look into this and learned that using style-loader is not compatible with apps that do server-side rendering since it's not possible to inject css into the DOM on the server-side (because there is no DOM). So I shifted to using a different build set up where the CSS is output to separate files. This means that using a component from the library will need two import statements. One for the component itself and the other for its CSS.

## Example

```diff
import Dots from "react-activity/dist/Dots"
+ import "react-activity/dist/Dots.css"
```

If using nextjs the css import will need to happen in `_app.js`.
